name: auto_route_example
description: Bottom navigation with auto_route and flutter_bloc
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  auto_route: ^0.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  auto_route_generator: ^0.6.10
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
